# Generated by Django 2.2.2 on 2019-09-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeedback',
            name='useful',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
