# Generated by Django 2.2.2 on 2019-09-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productfeedback_useful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeedback',
            name='useful',
            field=models.BooleanField(default=True),
        ),
    ]
