# Generated by Django 2.2.2 on 2019-09-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190916_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeedback',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
