# Generated by Django 2.2.2 on 2019-09-17 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productfeedback_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeedback',
            name='parentComment',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='products.ProductFeedback'),
            preserve_default=False,
        ),
    ]
