# Generated by Django 2.2.2 on 2019-09-17 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productfeedback_parentcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeedback',
            name='parentComment',
            field=models.ForeignKey(default=3083200227470499, on_delete=django.db.models.deletion.CASCADE, to='products.ProductFeedback'),
        ),
    ]
