# Generated by Django 2.2.2 on 2019-09-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20190917_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeedback',
            name='parentComment',
        ),
    ]
