# Generated by Django 2.2.2 on 2019-09-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productattribute_useful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='useful',
            field=models.BooleanField(null=True),
        ),
    ]
