# Generated by Django 2.2.2 on 2019-09-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20190917_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeedback',
            name='useful',
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='vote',
            field=models.BooleanField(null=True),
        ),
    ]
